//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Student_Praktica
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student
    {
        public int ID { get; set; }
        public int ID_Dartment { get; set; }
        public int ID_Group { get; set; }
        public string Name { get; set; }
        public string Patromic { get; set; }
        public string Surname { get; set; }
        public string Type_of_study { get; set; }
        public string Phone { get; set; }
    
        public virtual Department Department { get; set; }
        public virtual Group Group { get; set; }
    }
}
